# Generated by Django 5.2.2 on 2025-06-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MailMerge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smtpsetting',
            old_name='port',
            new_name='smtp_port',
        ),
    ]
