# Generated by Django 5.2.2 on 2025-06-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailMerge', '0002_rename_port_smtpsetting_smtp_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsetting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
